import pandas as pd
df = pd.read_csv('Maligno_y_Benigno.csv')
columna_sentencias = df['Sentence']
arreglo_palabras = columna_sentencias.str.split().tolist()
feature = [
    'select',
    'union',
    'update',
    'set',
    'alter',
    'where',
    'like',
    'from',
    'table',
    'database',
    'drop',
    'delete',
    'insert',
    'And | Or',
    'null',
    '=',
    'information_schema',
    'user',
    'version',
    'load_file',
    'save',
    '! | # | % | $ | NUL | SOH | STX | ETX | EOT | @',
    '&',
    '|',
    ',',
    ';',
    '+ | - | * | /',
    'commit | rollback | grant |revoke | declare | remove',
    'count(;)',
    '/* | */',
    '\\x',
    '\\u',
    'connection',
    'xor',
    'inner join',
    'file | load_file | load_data_infile | into_outfile | into_dumpfile',
    'OS | Operative System | exec',
    'count(STRING)',
    'count(SUBSTR)',
    '\\',
    'count(SUBSTRING)',
    'count(MID)',
    'count(ASC)', 
    'count(<)',
    'count(>)',
    'count(")',
    'count("")',
    'exists',
    'floor',
    'rand',
    'group',
    'order',
    'lenght',
    'ascii',
    'if',
    'count',
    'sleep',
    'between',
    'values',
    'delay',
    'wait',
    'benchmark'
    'indentity_insert',
    'truncate table',
    'username | password',
    'user | pass',
    '")"',
    'limit',
    'concat',
    'ne',
    'find',
    'eq | gt | gte | lt | it | lte | ite | in | nin',
    'mod | regex | text',
    'return',
    'return true | return 1',
    'exists', 
    'create',
    'show',
    'collection',
    'while(loop)',
    'hidden equality expression',
    'large expression',
]

funcion_conversion = lambda palabra: 1 if palabra in feature else 0

df['SentenciaConvertida'] = columna_sentencias.apply(lambda sentencia: [funcion_conversion(palabra) for palabra in sentencia.split()])

df_nuevo=df[['SentenciaConvertida']]
df_nuevo.to_csv('nuevo_dataset.csv', index=False)
print(df_nuevo)

